### ISSUE TITLE
BUG: no module `rechnung`

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/Rechnung#240]
I receive the following log, however, the apps seems to work as expected.
```
rechnung-rechnung-1  | During handling of the above exception, another exception occurred:
rechnung-rechnung-1  | 
rechnung-rechnung-1  | Traceback (most recent call last):
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 423, in run_from_argv
rechnung-rechnung-1  |     sys.exit(e.returncode)
rechnung-rechnung-1  |     ~~~~~~~~^^^^^^^^^^^^^^
rechnung-rechnung-1  | SystemExit: 1
rechnung-rechnung-1  | 
rechnung-rechnung-1  | During handling of the above exception, another exception occurred:
rechnung-rechnung-1  | 
rechnung-rechnung-1  | Traceback (most recent call last):
rechnung-rechnung-1  |   File "/usr/local/bin/django-admin", line 8, in <module>
rechnung-rechnung-1  |     sys.exit(execute_from_command_line())
rechnung-rechnung-1  |              ~~~~~~~~~~~~~~~~~~~~~~~~~^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
rechnung-rechnung-1  |     utility.execute()
rechnung-rechnung-1  |     ~~~~~~~~~~~~~~~^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
rechnung-rechnung-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
rechnung-rechnung-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 426, in run_from_argv
rechnung-rechnung-1  |     connections.close_all()
rechnung-rechnung-1  |     ~~~~~~~~~~~~~~~~~~~~~^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/utils/connection.py", line 84, in close_all
rechnung-rechnung-1  |     for conn in self.all(initialized_only=True):
rechnung-rechnung-1  |                 ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/utils/connection.py", line 78, in all
rechnung-rechnung-1  |     for alias in self
rechnung-rechnung-1  |                  ^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/utils/connection.py", line 73, in __iter__
rechnung-rechnung-1  |     return iter(self.settings)
rechnung-rechnung-1  |                 ^^^^^^^^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
rechnung-rechnung-1  |     res = instance.__dict__[self.name] = self.func(instance)
rechnung-rechnung-1  |                                          ~~~~~~~~~^^^^^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/utils/connection.py", line 45, in settings
rechnung-rechnung-1  |     self._settings = self.configure_settings(self._settings)
rechnung-rechnung-1  |                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 148, in configure_settings
rechnung-rechnung-1  |     databases = super().configure_settings(databases)
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/utils/connection.py", line 50, in configure_settings
rechnung-rechnung-1  |     settings = getattr(django_settings, self.settings_name)
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
rechnung-rechnung-1  |     self._setup(name)
rechnung-rechnung-1  |     ~~~~~~~~~~~^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
rechnung-rechnung-1  |     self._wrapped = Settings(settings_module)
rechnung-rechnung-1  |                     ~~~~~~~~^^^^^^^^^^^^^^^^^
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
rechnung-rechnung-1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
rechnung-rechnung-1  |   File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
rechnung-rechnung-1  |     return _bootstrap._gcd_import(name[level:], package, level)
rechnung-rechnung-1  |            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
rechnung-rechnung-1  |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
rechnung-rechnung-1  | ModuleNotFoundError: No module named 'rechnung'
```
docker compose:
```yaml                                                                                
version: '3'
services:
  rechnung:
    restart: always
    #build: . # Enable if you want to build from source
    image: ghcr.io/segelzwerg/segelzwerg/rechnung:latest
    ports:
      - "12321:8000" # You can change to any port you like.
    depends_on:
      - postgres
    env_file:
      - ./.env
  postgres:
    image: postgres:17
    volumes:
      - /media/usb/rechnung:/var/lib/postgresql/data/ # Enable if you want to use an external drive
      #- /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
```

.env

```env
ALLOWED_HOSTS=0.0.0.0,localhost,******
SECRET_KEY=******
DB_NAME=rechnung
DB_USER=*****
DB_PASSWORD=*****
DB_HOST=postgres
DB_PORT=5432
DJANGO_SETTINGS_MODULE=rechnung.prod_settings
```
